import { configureStore } from "@reduxjs/toolkit";
import { apiSlice } from "./api/apiSlice";
import authReducer from "./features/auth/authSlice"

const store = configureStore({
    reducer: {
        [apiSlice.reducerPath]: apiSlice.reducer,
        // automatically generated by the api slice
        // reducerPath is the name of the slice
        auth : authReducer
    },
    middleware: (getDefaultMiddleware) => {
        return getDefaultMiddleware().concat(apiSlice.middleware);
        // automatically generated by the api slice
        // middleware is the middleware that we need to add to our store
        // this need for rtks query to work with cache and other stuff
    },
    devTools: process.env.NODE_ENV !== "production",
});

export default store;